jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew build -Pmod_version="$(git describe --always --tags --first-parent
        | cut -c2-)"
    - continue-on-error: true
      name: Archive Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Artifacts
        path: dist/
    - continue-on-error: true
      name: Archive mapping.txt
      uses: actions/upload-artifact@v4
      with:
        name: Mappings
        path: mapping/
name: Java CI with Gradle
on:
  repository_dispatch:
    types: trigger-ga___gradle_build.yml
